bases:
  - environments.yaml
---
{{ readFile "hf-templates.yaml" }}

repositories:
  - name: crashteamdev
    url: https://crashteamdev.github.io/charts/
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: requarks
    url: https://charts.js.wiki
  - name: temporal
    url: https://go.temporal.io/helm-charts

releases:
  - name: ke-analytics
    <<: *generic_stateless
    installed: false
  - name: ke-space
    <<: *generic_stateless
    installed: false
  - name: uzum-space
    <<: *generic_stateless
    installed: false
  - name: styx
    <<: *generic_stateless
    installed: false
  - name: uzum-analytics
    <<: *generic_stateless
    installed: false
  - name: ke-data-scrapper
    <<: *generic_stateless
    installed: false
  - name: ke-landing
    <<: *generic_stateless
    installed: false
  - name: uzum-landing
    <<: *generic_stateless
    installed: false
  - name: uzum-data-scrapper
    <<: *generic_stateless
    installed: false
  - name: space-dashboard
    <<: *generic_stateless
    installed: false
  - name: space-gateway
    <<: *generic_stateless
    installed: false
  - name: charon
    <<: *generic_stateless
    installed: false
  - name: hermes
    <<: *generic_stateless
    installed: false
  - name: knowledge-doc
    <<: *generic_stateless
    installed: false
  - name: strapi
    <<: *default
    installed: false
    chart: crashteamdev/strapi-chart
    version: 0.1.1
  - name: temporal
    <<: *default
    installed: false
    chart: temporal/temporal
    version: 0.54.0
  - name: herald
    <<: *generic_stateless
    installed: false
  - name: chatgptbot
    <<: *generic_stateless
    installed: false
  - name: chainbrain-agent
    <<: *generic_stateless
    installed: false
  - name: n8n
    <<: *default
    installed: false
    chart: oci://8gears.container-registry.com/library/n8n
    version: 1.0.15
  - name: chatgptwebapp
    <<: *generic_stateless
    installed: false
