bases:
  - environments.yaml
---
{{ readFile "hf-templates.yaml" }}

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: crashteamdev
    url: https://crashteamdev.github.io/charts/

releases:
  - name: ke-analytics
    <<: *generic_stateless
#  - name: uzum-analytics
#    <<: *generic_stateless
  - name: ke-space
    <<: *generic_stateless
  - name: styx
    <<: *generic_stateless
#  - name: ke-data-scrapper
#    <<: *generic_stateless
  - name: ru-marketdb
    <<: *generic_stateless
