bases:
  - environments.yaml
---
{{ readFile "hf-templates.yaml" }}

repositories:
  - name: crashteamdev
    url: https://crashteamdev.github.io/charts/

releases:
  - name: endmake-web
    <<: *generic_stateless
  - name: endmake-worker
    <<: *generic_stateless
  - name: endmake-thumbor
    <<: *generic_stateless
  - name: endmake-landing
    <<: *generic_stateless
  - name: endmake-ru-redirect
    <<: *default
    chart: crashteamdev/raw
    version: 1.0.0
