bases:
  - environments.yaml
---
{{ readFile "hf-templates.yaml" }}

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: crashteamdev
    url: https://crashteamdev.github.io/charts/
  - name: requarks
    url: https://charts.js.wiki

releases:
  - name: ke-analytics
    <<: *generic_stateless
  - name: ke-space
    <<: *generic_stateless
  - name: uzum-space
    <<: *generic_stateless
  - name: styx
    <<: *generic_stateless
  - name: uzum-analytics
    <<: *generic_stateless
  - name: ke-data-scrapper
    <<: *generic_stateless
  - name: ke-landing
    <<: *generic_stateless
  - name: uzum-landing
    <<: *generic_stateless
  - name: uzum-data-scrapper
    <<: *generic_stateless
  - name: space-dashboard
    <<: *generic_stateless
  - name: space-gateway
    <<: *generic_stateless
  - name: charon
    <<: *generic_stateless
  - name: hermes
    <<: *generic_stateless
  - name: wiki-marketdb
    <<: *default
    chart: requarks/wiki
    version: v2.2.20
  - name: knowledge-doc
    <<: *generic_stateless
