bases:
  - environments.yaml
---
{{ readFile "hf-templates.yaml" }}

repositories:
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: crashteamdev
    url: https://crashteamdev.github.io/charts/
  - name: requarks
    url: https://charts.js.wiki
  - name: k8s-home-lab-repo
    url: https://k8s-home-lab.github.io/helm-charts/

releases:
  - name: ke-analytics
    <<: *generic_stateless
  - name: ke-space
    <<: *generic_stateless
  - name: uzum-space
    <<: *generic_stateless
  - name: styx
    <<: *generic_stateless
  - name: uzum-analytics
    <<: *generic_stateless
  - name: ke-data-scrapper
    <<: *generic_stateless
  - name: ke-landing
    <<: *generic_stateless
  - name: uzum-landing
    <<: *generic_stateless
  - name: uzum-data-scrapper
    <<: *generic_stateless
  - name: space-dashboard
    <<: *generic_stateless
  - name: space-gateway
    <<: *generic_stateless
  - name: charon
    <<: *generic_stateless
  - name: hermes
    <<: *generic_stateless
  - name: knowledge-doc
    <<: *generic_stateless
  - name: strapi
    <<: *default
    chart: crashteamdev/strapi-chart
    version: 0.1.1
  - name: herald
    <<: *generic_stateless
  - name: flaresolverr
    <<: *default
    chart: k8s-home-lab-repo/flaresolverr
    version: 6.0.3
