bases:
  - environments.yaml
---

{{ readFile "hf-templates.yaml" }}

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: crashteamdev
    url: https://crashteamdev.github.io/charts/
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
{{- if eq .Values.ingresscontroller.enabled true }}
- name: ingress
  <<: *infra_default
  chart: ingress-nginx/ingress-nginx
  namespace: ingress
{{- end }}
{{- if eq .Values.prometheus.enabled true }}
- name: prometheus
  <<: *infra_default
  chart: prometheus-community/kube-prometheus-stack
  version: 43.1.3
{{- end }}
