{{- $applicationName := .Release.Name -}}

server:
  port: {{ .Values.services.global.java.apiPort }}
  servlet:
    context-path: /space

logback:
  appender: JSON_K8S_CONSOLE

logging:
  level:
    "liquibase": INFO
    org.apache.http: INFO
    dev.crashteam.uzumspace.client.uzum: INFO

spring:
  application:
    name: {{ $applicationName }}
  webflux:
    base-path: /space

management:
  server:
    port: {{ .Values.services.global.java.managementPort }}
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: {{ $applicationName }}
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

service:
  proxy:
    url: http://styx:8080

repricer:
  productCron: 0 0 0/3 * * ?
  accountUpdateDataCron: 0 0 0/1 * * ?
  priceChangeCron: 0 0/15 * * * ?
  paymentCron: 0/15 * * * * ?
  accountInitializeCron: 0/20 * * * * ?
