name: Destroy terraform

on:
  workflow_dispatch:

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup access token
        run: |
          echo $YC_KEY >> $YC_SERVICE_ACCOUNT_KEY_FILE
          echo "YC_SERVICE_ACCOUNT_KEY_FILE=$YC_SERVICE_ACCOUNT_KEY_FILE" >> $GITHUB_ENV
        env:
          YC_KEY: ${{ secrets.YC_KEY }}
          YC_SERVICE_ACCOUNT_KEY_FILE: /tmp/sa-key.json

      - name: Terraform Init
        run: |
          cd yandex
          echo "TF_VAR_db_password=$DB_ADM_PASSWD" >> $GITHUB_ENV
          terraform init -backend-config="access_key=$AWS_ACCESS_KEY_ID" -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DB_ADM_PASSWD: ${{ secrets.DB_ADM_PASSWD }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - name: Terraform Destroy
        if:  ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          cd yandex
          terraform destroy -auto-approve
